# Generated by Django 6.0.3 on 2026-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='predicted_style',
            field=models.CharField(choices=[('formal', 'Formal'), ('sporty', 'Sporty'), ('casual', 'Casual'), ('unknow', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='style_confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
