# Generated by Django 6.0.3 on 2026-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_clothingitem_predicted_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='predicted_style',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='style_confidence',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('blazer', 'Blazer'), ('hoodie', 'Hoodie'), ('trousers', 'Trousers'), ('jeans', 'Jeans'), ('trackpants', 'Trackpants'), ('shorts', 'Shorts'), ('cargos', 'Cargos'), ('chinos', 'Chinos'), ('formal_shoes', 'Formal Shoes'), ('loafers', 'Loafers'), ('sneakers', 'Sneakers'), ('slides', 'Slides'), ('sports_shoes', 'Sports Shoes'), ('slippers', 'Slippers')], default='tshirt', max_length=30),
        ),
    ]
