# Generated by Django 6.0.3 on 2026-04-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_remove_clothingitem_predicted_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
