# Generated by Django 6.0.3 on 2026-04-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_clothingitem_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20)),
                ('generated_score', models.FloatField()),
                ('user_rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_bottom', to='wardrobe.clothingitem')),
                ('shoe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated_shoe', to='wardrobe.clothingitem')),
                ('top_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_top', to='wardrobe.clothingitem')),
            ],
            options={
                'unique_together': {('top_item', 'bottom_item', 'shoe_item', 'style')},
            },
        ),
    ]
