# Generated by Django 6.0.3 on 2026-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_outfitrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='breathability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
