# Generated by Django 6.0.3 on 2026-06-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_clothingitem_breathability_clothingitem_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color_percentages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='dominant_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='histogram',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClothingFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.JSONField()),
                ('histogram', models.JSONField()),
                ('material', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.clothingitem')),
            ],
        ),
    ]
