# Generated by Django 6.0.3 on 2026-06-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_clothingitem_ai_processed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothingFeatures',
        ),
    ]
